database:
  host: 127.0.0.1       # 替换为你的数据库主机地址
  database: tushare # 替换为你的数据库名称
  user: root       # 替换为你的数据库用户名
  password: liuzheng  # 替换为你的数据库密码
token: 49dd4d99eb45ca99bf9c6e13690b6b79daa756974e0fa235b6add6c3