"""
财务数据 ORM 模型
"""
from sqlalchemy import Column, Integer, String, Float
from mysql_connect.db import Base


class FinancialData(Base):
    """财务指标数据"""
    __tablename__ = 'financial_data'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    ts_code = Column(String(20), index=True)
    ann_date = Column(String(10))
    end_date = Column(String(10), index=True)
    eps = Column(Float)
    dt_eps = Column(Float)
    total_revenue_ps = Column(Float)
    revenue_ps = Column(Float)
    capital_rese_ps = Column(Float)
    surplus_rese_ps = Column(Float)
    undist_profit_ps = Column(Float)
    extra_item = Column(Float)
    profit_dedt = Column(Float)
    gross_margin = Column(Float)
    current_ratio = Column(Float)
    quick_ratio = Column(Float)
    cash_ratio = Column(Float)
    invturn_days = Column(Float)
    arturn_days = Column(Float)
    inv_turn = Column(Float)
    ar_turn = Column(Float)
    ca_turn = Column(Float)
    fa_turn = Column(Float)
    assets_turn = Column(Float)
    op_income = Column(Float)
    valuechange_income = Column(Float)
    interst_income = Column(Float)
    daa = Column(Float)
    ebit = Column(Float)
    ebitda = Column(Float)
    fcff = Column(Float)
    fcfe = Column(Float)
    current_exint = Column(Float)
    noncurrent_exint = Column(Float)
    interestdebt = Column(Float)
    netdebt = Column(Float)
    tangible_asset = Column(Float)
    working_capital = Column(Float)
    networking_capital = Column(Float)
    invest_capital = Column(Float)
    retained_earnings = Column(Float)
    diluted2_eps = Column(Float)
    bps = Column(Float)
    ocfps = Column(Float)
    retainedps = Column(Float)
    cfps = Column(Float)
    ebit_ps = Column(Float)
    fcff_ps = Column(Float)
    fcfe_ps = Column(Float)
    netprofit_margin = Column(Float)
    grossprofit_margin = Column(Float)
    cogs_of_sales = Column(Float)
    expense_of_sales = Column(Float)
    profit_to_gr = Column(Float)
    saleexp_to_gr = Column(Float)
    adminexp_of_gr = Column(Float)
    finaexp_of_gr = Column(Float)
    impai_ttm = Column(Float)
    gc_of_gr = Column(Float)
    op_of_gr = Column(Float)
    ebit_of_gr = Column(Float)
    roe = Column(Float)
    roe_waa = Column(Float)
    roe_dt = Column(Float)
    roa = Column(Float)
    npta = Column(Float)
    roic = Column(Float)
    roe_yearly = Column(Float)
    roa2_yearly = Column(Float)
    roe_avg = Column(Float)
    opincome_of_ebt = Column(Float)
    investincome_of_ebt = Column(Float)
    n_op_profit_of_ebt = Column(Float)
    tax_to_ebt = Column(Float)
    dtprofit_to_profit = Column(Float)
    salescash_to_or = Column(Float)
    ocf_to_or = Column(Float)
    ocf_to_opincome = Column(Float)
    capitalized_to_da = Column(Float)
    debt_to_assets = Column(Float)
    assets_to_eqt = Column(Float)
    dp_assets_to_eqt = Column(Float)
    ca_to_assets = Column(Float)
    nca_to_assets = Column(Float)
    tbassets_to_totalassets = Column(Float)
    int_to_talcap = Column(Float)
    eqt_to_talcapital = Column(Float)
    currentdebt_to_debt = Column(Float)
    longdeb_to_debt = Column(Float)
    ocf_to_shortdebt = Column(Float)
    debt_to_eqt = Column(Float)
    eqt_to_debt = Column(Float)
    eqt_to_interestdebt = Column(Float)
    tangibleasset_to_debt = Column(Float)
    tangasset_to_intdebt = Column(Float)
    tangibleasset_to_netdebt = Column(Float)
    ocf_to_debt = Column(Float)
    ocf_to_interestdebt = Column(Float)
    ocf_to_netdebt = Column(Float)
    ebit_to_interest = Column(Float)
    longdebt_to_workingcapital = Column(Float)
    ebitda_to_debt = Column(Float)
    turn_days = Column(Float)
    roa_yearly = Column(Float)
    roa_dp = Column(Float)
    fixed_assets = Column(Float)
    profit_prefin_exp = Column(Float)
    non_op_profit = Column(Float)
    op_to_ebt = Column(Float)
    nop_to_ebt = Column(Float)
    ocf_to_profit = Column(Float)
    cash_to_liqdebt = Column(Float)
    cash_to_liqdebt_withinterest = Column(Float)
    op_to_liqdebt = Column(Float)
    op_to_debt = Column(Float)
    roic_yearly = Column(Float)
    total_fa_trun = Column(Float)
    profit_to_op = Column(Float)
    q_opincome = Column(Float)
    q_investincome = Column(Float)
    q_dtprofit = Column(Float)
    q_eps = Column(Float)
    q_netprofit_margin = Column(Float)
    q_gsprofit_margin = Column(Float)
    q_exp_to_sales = Column(Float)
    q_profit_to_gr = Column(Float)
    q_saleexp_to_gr = Column(Float)
    q_adminexp_to_gr = Column(Float)
    q_finaexp_to_gr = Column(Float)
    q_impair_to_gr_ttm = Column(Float)
    q_gc_to_gr = Column(Float)
    q_op_to_gr = Column(Float)
    q_roe = Column(Float)
    q_dt_roe = Column(Float)
    q_npta = Column(Float)
    q_opincome_to_ebt = Column(Float)
    q_investincome_to_ebt = Column(Float)
    q_dtprofit_to_profit = Column(Float)
    q_salescash_to_or = Column(Float)
    q_ocf_to_sales = Column(Float)
    q_ocf_to_or = Column(Float)
    basic_eps_yoy = Column(Float)
    dt_eps_yoy = Column(Float)
    cfps_yoy = Column(Float)
    op_yoy = Column(Float)
    ebt_yoy = Column(Float)
    netprofit_yoy = Column(Float)
    dt_netprofit_yoy = Column(Float)
    ocf_yoy = Column(Float)
    roe_yoy = Column(Float)
    bps_yoy = Column(Float)
    assets_yoy = Column(Float)
    eqt_yoy = Column(Float)
    tr_yoy = Column(Float)
    or_yoy = Column(Float)
    q_gr_yoy = Column(Float)
    q_gr_qoq = Column(Float)
    q_sales_yoy = Column(Float)
    q_sales_qoq = Column(Float)
    q_op_yoy = Column(Float)
    q_op_qoq = Column(Float)
    q_profit_yoy = Column(Float)
    q_profit_qoq = Column(Float)
    q_netprofit_yoy = Column(Float)
    q_netprofit_qoq = Column(Float)
    equity_yoy = Column(Float)
    rd_exp = Column(Float)
    update_flag = Column(String(5))
    
    # 常用 getter 方法
    def get_ts_code(self):
        return self.ts_code
    
    def get_ann_date(self):
        return self.ann_date
    
    def get_end_date(self):
        return self.end_date
    
    def get_eps(self):
        return self.eps
    
    def get_roe(self):
        return self.roe
    
    def get_profit_dedt(self):
        return self.profit_dedt
    
    def set_id(self, id):
        self.id = id
    
    def to_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}
    
    def to_dict_with_backticks(self, contains_id=True):
        data_dict = self.to_dict()
        if not contains_id:
            data_dict.pop('id', None)
        return {f'`{key}`': value for key, value in sorted(data_dict.items())}
