CREATE TABLE `stock_basic` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `ts_code` varchar(20) DEFAULT NULL COMMENT 'TS代码',
  `symbol` varchar(20) DEFAULT NULL COMMENT '股票代码',
  `name` varchar(100) DEFAULT NULL COMMENT '股票名称',
  `area` varchar(50) DEFAULT NULL COMMENT '地域',
  `industry` varchar(100) DEFAULT NULL COMMENT '所属行业',
  `fullname` varchar(200) DEFAULT NULL COMMENT '股票全称',
  `enname` varchar(200) DEFAULT NULL COMMENT '英文全称',
  `cnspell` varchar(100) DEFAULT NULL COMMENT '拼音缩写',
  `market` varchar(20) DEFAULT NULL COMMENT '市场类型',
  `exchange` varchar(20) DEFAULT NULL COMMENT '交易所代码',
  `curr_type` varchar(10) DEFAULT NULL COMMENT '交易货币',
  `list_status` varchar(10) DEFAULT NULL COMMENT '上市状态 L上市 D退市 P暂停上市',
  `list_date` varchar(20) DEFAULT NULL COMMENT '上市日期',
  `delist_date` varchar(20) DEFAULT NULL COMMENT '退市日期',
  `is_hs` varchar(10) DEFAULT NULL COMMENT '是否沪深港通标的，N否 H沪股通 S深股通',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ts_code` (`ts_code`) COMMENT 'TS代码唯一索引',
  KEY `idx_symbol` (`symbol`) COMMENT '股票代码索引',
  KEY `idx_name` (`name`) COMMENT '股票名称索引',
  KEY `idx_list_status` (`list_status`) COMMENT '上市状态索引',
  KEY `idx_area` (`area`) COMMENT '地域索引',
  KEY `idx_industry` (`industry`) COMMENT '行业索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMEN