CREATE TABLE `ts_stock_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ts_code` varchar(20) CHARACTER SET latin1 DEFAULT NULL COMMENT '指数代码',
  `trade_date` date DEFAULT NULL COMMENT '交易日',
  `close` double(255,4) DEFAULT NULL COMMENT '收盘点位',
  `open` double(255,4) DEFAULT NULL COMMENT '开盘点位',
  `high` double(255,4) DEFAULT NULL COMMENT '最高点位',
  `low` double(255,4) DEFAULT NULL COMMENT '最低点位',
  `pre_close` double(255,4) DEFAULT NULL COMMENT '昨日收盘点',
  `change` double(255,4) DEFAULT NULL COMMENT '涨跌点',
  `pct_chg` double(255,4) DEFAULT NULL COMMENT '涨跌幅（%）',
  `vol` double(255,4) DEFAULT NULL COMMENT '成交量（手）',
  `amount` double(255,4) DEFAULT NULL COMMENT '成交额（千元）',
  `average_date` int(255) DEFAULT NULL COMMENT '日线',
  `average_amount` double(255,4) DEFAULT NULL COMMENT '日线值',
  `deviation_rate` double(255,5) DEFAULT NULL COMMENT '偏移率',
  `name` varchar(255) DEFAULT NULL COMMENT '指数名称',
  `pe_weight` float(255,4) DEFAULT NULL COMMENT 'pe加权值',
  `pe_ttm_weight` float(255,0) DEFAULT NULL COMMENT 'pe_ttm加权值',
  `pb_weight` float(255,4) DEFAULT NULL COMMENT 'pb加权值',
  `pe` float(255,4) DEFAULT NULL COMMENT 'pe等权值',
  `pb` float(255,4) DEFAULT NULL COMMENT 'pb等权值',
  `pe_ttm` float(255,4) DEFAULT NULL COMMENT 'pe_ttm等权值',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14064 DEFAULT CHARSET=utf8mb4